server:
  port: 4444
spring:
  application:
    name: psring-zuul-router
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    add:
      path: /add/**
      url: http://127.0.0.1:3333/add